name: admob_manager_flutter
description: Admob Manager is a wrapper around famous ad packages which let you integrate ads easily
version: 2.3.4
homepage: https://github.com/furkankurt/admob-manager
repository: https://github.com/furkankurt/admob-manager

environment:
  sdk: ">=3.3.4 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  app_tracking_transparency: ^2.0.5
  google_mobile_ads: ^5.1.0
  collection: ^1.18.0
  logger: ^2.3.0

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
